import { MigrationInterface, QueryRunner } from "typeorm";

export class Prueba11746075352713 implements MigrationInterface {
    name = 'Prueba11746075352713'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`submodulos\` DROP FOREIGN KEY \`submodulos_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` DROP FOREIGN KEY \`foro_comentarios_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` DROP FOREIGN KEY \`foro_comentarios_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`parametros_proyecto\` DROP FOREIGN KEY \`parametros_proyecto_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` DROP FOREIGN KEY \`rentabilidad_proyecto_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`eventos\` DROP FOREIGN KEY \`eventos_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`eventos\` DROP FOREIGN KEY \`eventos_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`agendas\` DROP FOREIGN KEY \`agendas_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`agendas\` DROP FOREIGN KEY \`agendas_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`agendas\` DROP FOREIGN KEY \`agendas_ibfk_3\``);
        await queryRunner.query(`ALTER TABLE \`tareas\` DROP FOREIGN KEY \`tareas_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`transacciones\` DROP FOREIGN KEY \`transacciones_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`transacciones\` DROP FOREIGN KEY \`transacciones_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`reportes\` DROP FOREIGN KEY \`reportes_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`reportes\` DROP FOREIGN KEY \`reportes_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` DROP FOREIGN KEY \`alertas_inteligentes_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`proyectos\` DROP FOREIGN KEY \`proyectos_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`proyectos\` DROP FOREIGN KEY \`proyectos_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`proyectos\` DROP FOREIGN KEY \`proyectos_ibfk_3\``);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` DROP FOREIGN KEY \`notificaciones_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` DROP FOREIGN KEY \`soporte_tecnico_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`usuario_roles\` DROP FOREIGN KEY \`usuario_roles_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`usuario_roles\` DROP FOREIGN KEY \`usuario_roles_ibfk_2\``);
        await queryRunner.query(`DROP INDEX \`modulo_id\` ON \`submodulos\``);
        await queryRunner.query(`DROP INDEX \`modulo_id\` ON \`foro_comentarios\``);
        await queryRunner.query(`DROP INDEX \`usuario_id\` ON \`foro_comentarios\``);
        await queryRunner.query(`DROP INDEX \`nombre\` ON \`modulos\``);
        await queryRunner.query(`DROP INDEX \`proyecto_id\` ON \`parametros_proyecto\``);
        await queryRunner.query(`DROP INDEX \`proyecto_id\` ON \`rentabilidad_proyecto\``);
        await queryRunner.query(`DROP INDEX \`nombre\` ON \`tipos_evento\``);
        await queryRunner.query(`DROP INDEX \`proyecto_id\` ON \`eventos\``);
        await queryRunner.query(`DROP INDEX \`tipo_evento_id\` ON \`eventos\``);
        await queryRunner.query(`DROP INDEX \`evento_id\` ON \`agendas\``);
        await queryRunner.query(`DROP INDEX \`proyecto_id\` ON \`agendas\``);
        await queryRunner.query(`DROP INDEX \`tarea_id\` ON \`agendas\``);
        await queryRunner.query(`DROP INDEX \`proyecto_id\` ON \`tareas\``);
        await queryRunner.query(`DROP INDEX \`nombre\` ON \`categorias_transaccion\``);
        await queryRunner.query(`DROP INDEX \`categoria_id\` ON \`transacciones\``);
        await queryRunner.query(`DROP INDEX \`proyecto_id\` ON \`transacciones\``);
        await queryRunner.query(`DROP INDEX \`nombre\` ON \`formatos_reporte\``);
        await queryRunner.query(`DROP INDEX \`formato_id\` ON \`reportes\``);
        await queryRunner.query(`DROP INDEX \`proyecto_id\` ON \`reportes\``);
        await queryRunner.query(`DROP INDEX \`proyecto_id\` ON \`alertas_inteligentes\``);
        await queryRunner.query(`DROP INDEX \`modulo_id\` ON \`proyectos\``);
        await queryRunner.query(`DROP INDEX \`submodulo_id\` ON \`proyectos\``);
        await queryRunner.query(`DROP INDEX \`usuario_id\` ON \`proyectos\``);
        await queryRunner.query(`DROP INDEX \`usuario_id\` ON \`notificaciones\``);
        await queryRunner.query(`DROP INDEX \`usuario_id\` ON \`soporte_tecnico\``);
        await queryRunner.query(`DROP INDEX \`nombre\` ON \`roles\``);
        await queryRunner.query(`DROP INDEX \`email\` ON \`usuarios\``);
        await queryRunner.query(`DROP INDEX \`rol_id\` ON \`usuario_roles\``);
        await queryRunner.query(`DROP INDEX \`usuario_id\` ON \`usuario_roles\``);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` DROP COLUMN \`fecha_creado\``);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` DROP COLUMN \`rentabilidad\``);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` DROP COLUMN \`fecha_calculo\``);
        await queryRunner.query(`ALTER TABLE \`agendas\` DROP COLUMN \`fecha_evento\``);
        await queryRunner.query(`ALTER TABLE \`transacciones\` DROP COLUMN \`tipo\``);
        await queryRunner.query(`ALTER TABLE \`transacciones\` DROP COLUMN \`valor\``);
        await queryRunner.query(`ALTER TABLE \`reportes\` DROP COLUMN \`tipo_reporte\``);
        await queryRunner.query(`ALTER TABLE \`reportes\` DROP COLUMN \`fecha_generado\``);
        await queryRunner.query(`ALTER TABLE \`reportes\` DROP COLUMN \`url_archivo\``);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` DROP COLUMN \`mensaje_alerta\``);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` DROP COLUMN \`tipo_alerta\``);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` DROP COLUMN \`fecha_creacion\``);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` DROP COLUMN \`fecha_creacion\``);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` DROP COLUMN \`fecha_creacion\``);
        await queryRunner.query(`ALTER TABLE \`submodulos\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`submodulos\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`submodulos\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` ADD \`imagen_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` ADD \`likes\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` ADD \`comentario_padre_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`modulos\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`modulos\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`modulos\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`parametros_proyecto\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`parametros_proyecto\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`parametros_proyecto\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` ADD \`fecha\` date NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` ADD \`inversion_inicial\` decimal(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` ADD \`ingresos_totales\` decimal(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` ADD \`gastos_totales\` decimal(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` ADD \`rentabilidad_neta\` decimal(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` ADD \`roi\` decimal(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tipos_evento\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tipos_evento\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tipos_evento\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`eventos\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`eventos\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`eventos\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`agendas\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`agendas\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`agendas\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`agendas\` ADD \`fecha\` date NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`agendas\` ADD \`tipo\` enum ('tarea', 'evento') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tareas\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tareas\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tareas\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`categorias_transaccion\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`categorias_transaccion\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`categorias_transaccion\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`categorias_transaccion\` ADD \`tipo\` enum ('ingreso', 'egreso') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`categorias_transaccion\` ADD \`descripcion\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`transacciones\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`transacciones\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`transacciones\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`transacciones\` ADD \`monto\` decimal(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`transacciones\` ADD \`comprobante_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`formatos_reporte\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`formatos_reporte\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`formatos_reporte\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`formatos_reporte\` ADD \`estructura\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`formatos_reporte\` ADD \`descripcion\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`reportes\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`reportes\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`reportes\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`reportes\` ADD \`titulo\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reportes\` ADD \`fecha_inicio\` date NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reportes\` ADD \`fecha_fin\` date NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reportes\` ADD \`datos\` json NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reportes\` ADD \`archivo_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` ADD \`nombre\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` ADD \`condicion\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` ADD \`mensaje\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` ADD \`activa\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`proyectos\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`proyectos\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`proyectos\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` ADD \`titulo\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` ADD \`tipo\` enum ('sistema', 'alerta', 'recordatorio', 'informacion') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` ADD \`respuesta\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` ADD \`adjunto_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD \`password\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuario_roles\` ADD PRIMARY KEY (\`usuario_id\`, \`rol_id\`)`);
        await queryRunner.query(`ALTER TABLE \`submodulos\` DROP COLUMN \`nombre\``);
        await queryRunner.query(`ALTER TABLE \`submodulos\` ADD \`nombre\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`submodulos\` CHANGE \`modulo_id\` \`modulo_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` DROP COLUMN \`titulo\``);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` ADD \`titulo\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` CHANGE \`contenido\` \`contenido\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` CHANGE \`usuario_id\` \`usuario_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` CHANGE \`modulo_id\` \`modulo_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`modulos\` DROP COLUMN \`nombre\``);
        await queryRunner.query(`ALTER TABLE \`modulos\` ADD \`nombre\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`modulos\` ADD UNIQUE INDEX \`IDX_9dd861f2d25942a1c2c563af05\` (\`nombre\`)`);
        await queryRunner.query(`ALTER TABLE \`parametros_proyecto\` DROP COLUMN \`parametro_nombre\``);
        await queryRunner.query(`ALTER TABLE \`parametros_proyecto\` ADD \`parametro_nombre\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`parametros_proyecto\` DROP COLUMN \`valor\``);
        await queryRunner.query(`ALTER TABLE \`parametros_proyecto\` ADD \`valor\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`parametros_proyecto\` CHANGE \`proyecto_id\` \`proyecto_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` CHANGE \`proyecto_id\` \`proyecto_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tipos_evento\` DROP COLUMN \`nombre\``);
        await queryRunner.query(`ALTER TABLE \`tipos_evento\` ADD \`nombre\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tipos_evento\` ADD UNIQUE INDEX \`IDX_4752b8447cc578fd3719ab5499\` (\`nombre\`)`);
        await queryRunner.query(`ALTER TABLE \`eventos\` CHANGE \`descripcion\` \`descripcion\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`eventos\` CHANGE \`fecha_evento\` \`fecha_evento\` date NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`eventos\` CHANGE \`tiene_gasto\` \`tiene_gasto\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`eventos\` CHANGE \`proyecto_id\` \`proyecto_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`eventos\` CHANGE \`tipo_evento_id\` \`tipo_evento_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`agendas\` CHANGE \`proyecto_id\` \`proyecto_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tareas\` DROP COLUMN \`titulo\``);
        await queryRunner.query(`ALTER TABLE \`tareas\` ADD \`titulo\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tareas\` CHANGE \`fecha\` \`fecha\` date NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tareas\` CHANGE \`recordatorio\` \`recordatorio\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`tareas\` CHANGE \`proyecto_id\` \`proyecto_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`categorias_transaccion\` DROP COLUMN \`nombre\``);
        await queryRunner.query(`ALTER TABLE \`categorias_transaccion\` ADD \`nombre\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`transacciones\` CHANGE \`fecha\` \`fecha\` date NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`transacciones\` DROP COLUMN \`descripcion\``);
        await queryRunner.query(`ALTER TABLE \`transacciones\` ADD \`descripcion\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`transacciones\` CHANGE \`proyecto_id\` \`proyecto_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`transacciones\` CHANGE \`categoria_id\` \`categoria_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`formatos_reporte\` DROP COLUMN \`nombre\``);
        await queryRunner.query(`ALTER TABLE \`formatos_reporte\` ADD \`nombre\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reportes\` CHANGE \`proyecto_id\` \`proyecto_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reportes\` CHANGE \`formato_id\` \`formato_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` CHANGE \`proyecto_id\` \`proyecto_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`proyectos\` DROP COLUMN \`nombre\``);
        await queryRunner.query(`ALTER TABLE \`proyectos\` ADD \`nombre\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`proyectos\` DROP COLUMN \`ubicacion\``);
        await queryRunner.query(`ALTER TABLE \`proyectos\` ADD \`ubicacion\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`proyectos\` CHANGE \`fecha_inicio\` \`fecha_inicio\` date NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`proyectos\` CHANGE \`usuario_id\` \`usuario_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`proyectos\` CHANGE \`modulo_id\` \`modulo_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`proyectos\` CHANGE \`submodulo_id\` \`submodulo_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` CHANGE \`mensaje\` \`mensaje\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` CHANGE \`leida\` \`leida\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` CHANGE \`usuario_id\` \`usuario_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` DROP COLUMN \`asunto\``);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` ADD \`asunto\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` CHANGE \`mensaje\` \`mensaje\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` CHANGE \`estado\` \`estado\` enum ('abierto', 'en_proceso', 'resuelto', 'cerrado') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` CHANGE \`usuario_id\` \`usuario_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`nombre\``);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`nombre\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD UNIQUE INDEX \`IDX_a5be7aa67e759e347b1c6464e1\` (\`nombre\`)`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP COLUMN \`nombre\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD \`nombre\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD \`email\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD UNIQUE INDEX \`IDX_446adfc18b35418aac32ae0b7b\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP COLUMN \`telefono\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD \`telefono\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`tipo_autenticacion\` \`tipo_autenticacion\` enum ('google', 'telefono') NOT NULL DEFAULT 'telefono'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`es_pro\` \`es_pro\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`fecha_registro\` \`fecha_registro\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`usuario_roles\` CHANGE \`usuario_id\` \`usuario_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`usuario_roles\` CHANGE \`rol_id\` \`rol_id\` int NOT NULL`);
        await queryRunner.query(`CREATE INDEX \`IDX_f4660653ecea0eef621bae5209\` ON \`usuario_roles\` (\`usuario_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_0a60de73dab09515692949c13a\` ON \`usuario_roles\` (\`rol_id\`)`);
        await queryRunner.query(`ALTER TABLE \`submodulos\` ADD CONSTRAINT \`FK_a571beaa75d1e4b9650185219ff\` FOREIGN KEY (\`modulo_id\`) REFERENCES \`modulos\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` ADD CONSTRAINT \`FK_29274a9f99110ccbcca153be666\` FOREIGN KEY (\`usuario_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` ADD CONSTRAINT \`FK_07810925e498d3ef1c8ccf7d1cc\` FOREIGN KEY (\`modulo_id\`) REFERENCES \`modulos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`parametros_proyecto\` ADD CONSTRAINT \`FK_7e74dd0d820ec94a823ec69fecc\` FOREIGN KEY (\`proyecto_id\`) REFERENCES \`proyectos\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` ADD CONSTRAINT \`FK_dfacaddcf77fd7205c4b0bb5c36\` FOREIGN KEY (\`proyecto_id\`) REFERENCES \`proyectos\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`eventos\` ADD CONSTRAINT \`FK_4ac14529d3179f5da777d323164\` FOREIGN KEY (\`proyecto_id\`) REFERENCES \`proyectos\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`eventos\` ADD CONSTRAINT \`FK_5e788d9858275537bcb858ac0f8\` FOREIGN KEY (\`tipo_evento_id\`) REFERENCES \`tipos_evento\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`agendas\` ADD CONSTRAINT \`FK_7f15d686918ee6a13d46d949f76\` FOREIGN KEY (\`proyecto_id\`) REFERENCES \`proyectos\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`agendas\` ADD CONSTRAINT \`FK_c5f4d33f1bea90db1d2cbef44ab\` FOREIGN KEY (\`tarea_id\`) REFERENCES \`tareas\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`agendas\` ADD CONSTRAINT \`FK_88ce128a6e6e349cb7a6d6b867f\` FOREIGN KEY (\`evento_id\`) REFERENCES \`eventos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tareas\` ADD CONSTRAINT \`FK_ea21da74a19bb717109cb33ea9e\` FOREIGN KEY (\`proyecto_id\`) REFERENCES \`proyectos\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transacciones\` ADD CONSTRAINT \`FK_1f70f6ea55e1b87ae6cc620ba1a\` FOREIGN KEY (\`proyecto_id\`) REFERENCES \`proyectos\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transacciones\` ADD CONSTRAINT \`FK_deddbcadce68c9bacb42b3eb675\` FOREIGN KEY (\`categoria_id\`) REFERENCES \`categorias_transaccion\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reportes\` ADD CONSTRAINT \`FK_019d5f405c7356923eef6a0fbcb\` FOREIGN KEY (\`proyecto_id\`) REFERENCES \`proyectos\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reportes\` ADD CONSTRAINT \`FK_fde8c66011ac247d3f06d8d17e0\` FOREIGN KEY (\`formato_id\`) REFERENCES \`formatos_reporte\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` ADD CONSTRAINT \`FK_043af714f46df623131cf3022d7\` FOREIGN KEY (\`proyecto_id\`) REFERENCES \`proyectos\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`proyectos\` ADD CONSTRAINT \`FK_16c36301a6281da7a1f71af6569\` FOREIGN KEY (\`usuario_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`proyectos\` ADD CONSTRAINT \`FK_332b1dd04a2fdeadf1b4c959cba\` FOREIGN KEY (\`modulo_id\`) REFERENCES \`modulos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`proyectos\` ADD CONSTRAINT \`FK_a3bcd2f7d1b82ade146fe752eb9\` FOREIGN KEY (\`submodulo_id\`) REFERENCES \`submodulos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` ADD CONSTRAINT \`FK_2c6341d5bd206ff522b35aa6b69\` FOREIGN KEY (\`usuario_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` ADD CONSTRAINT \`FK_05881aa52825b5e3fae2790609f\` FOREIGN KEY (\`usuario_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`usuario_roles\` ADD CONSTRAINT \`FK_f4660653ecea0eef621bae52097\` FOREIGN KEY (\`usuario_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`usuario_roles\` ADD CONSTRAINT \`FK_0a60de73dab09515692949c13a5\` FOREIGN KEY (\`rol_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`usuario_roles\` DROP FOREIGN KEY \`FK_0a60de73dab09515692949c13a5\``);
        await queryRunner.query(`ALTER TABLE \`usuario_roles\` DROP FOREIGN KEY \`FK_f4660653ecea0eef621bae52097\``);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` DROP FOREIGN KEY \`FK_05881aa52825b5e3fae2790609f\``);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` DROP FOREIGN KEY \`FK_2c6341d5bd206ff522b35aa6b69\``);
        await queryRunner.query(`ALTER TABLE \`proyectos\` DROP FOREIGN KEY \`FK_a3bcd2f7d1b82ade146fe752eb9\``);
        await queryRunner.query(`ALTER TABLE \`proyectos\` DROP FOREIGN KEY \`FK_332b1dd04a2fdeadf1b4c959cba\``);
        await queryRunner.query(`ALTER TABLE \`proyectos\` DROP FOREIGN KEY \`FK_16c36301a6281da7a1f71af6569\``);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` DROP FOREIGN KEY \`FK_043af714f46df623131cf3022d7\``);
        await queryRunner.query(`ALTER TABLE \`reportes\` DROP FOREIGN KEY \`FK_fde8c66011ac247d3f06d8d17e0\``);
        await queryRunner.query(`ALTER TABLE \`reportes\` DROP FOREIGN KEY \`FK_019d5f405c7356923eef6a0fbcb\``);
        await queryRunner.query(`ALTER TABLE \`transacciones\` DROP FOREIGN KEY \`FK_deddbcadce68c9bacb42b3eb675\``);
        await queryRunner.query(`ALTER TABLE \`transacciones\` DROP FOREIGN KEY \`FK_1f70f6ea55e1b87ae6cc620ba1a\``);
        await queryRunner.query(`ALTER TABLE \`tareas\` DROP FOREIGN KEY \`FK_ea21da74a19bb717109cb33ea9e\``);
        await queryRunner.query(`ALTER TABLE \`agendas\` DROP FOREIGN KEY \`FK_88ce128a6e6e349cb7a6d6b867f\``);
        await queryRunner.query(`ALTER TABLE \`agendas\` DROP FOREIGN KEY \`FK_c5f4d33f1bea90db1d2cbef44ab\``);
        await queryRunner.query(`ALTER TABLE \`agendas\` DROP FOREIGN KEY \`FK_7f15d686918ee6a13d46d949f76\``);
        await queryRunner.query(`ALTER TABLE \`eventos\` DROP FOREIGN KEY \`FK_5e788d9858275537bcb858ac0f8\``);
        await queryRunner.query(`ALTER TABLE \`eventos\` DROP FOREIGN KEY \`FK_4ac14529d3179f5da777d323164\``);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` DROP FOREIGN KEY \`FK_dfacaddcf77fd7205c4b0bb5c36\``);
        await queryRunner.query(`ALTER TABLE \`parametros_proyecto\` DROP FOREIGN KEY \`FK_7e74dd0d820ec94a823ec69fecc\``);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` DROP FOREIGN KEY \`FK_07810925e498d3ef1c8ccf7d1cc\``);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` DROP FOREIGN KEY \`FK_29274a9f99110ccbcca153be666\``);
        await queryRunner.query(`ALTER TABLE \`submodulos\` DROP FOREIGN KEY \`FK_a571beaa75d1e4b9650185219ff\``);
        await queryRunner.query(`DROP INDEX \`IDX_0a60de73dab09515692949c13a\` ON \`usuario_roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_f4660653ecea0eef621bae5209\` ON \`usuario_roles\``);
        await queryRunner.query(`ALTER TABLE \`usuario_roles\` CHANGE \`rol_id\` \`rol_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`usuario_roles\` CHANGE \`usuario_id\` \`usuario_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`fecha_registro\` \`fecha_registro\` timestamp NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`es_pro\` \`es_pro\` tinyint(1) NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`tipo_autenticacion\` \`tipo_autenticacion\` enum ('google', 'telefono') NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP COLUMN \`telefono\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD \`telefono\` varchar(15) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP INDEX \`IDX_446adfc18b35418aac32ae0b7b\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD \`email\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP COLUMN \`nombre\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD \`nombre\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP INDEX \`IDX_a5be7aa67e759e347b1c6464e1\``);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`nombre\``);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`nombre\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` CHANGE \`usuario_id\` \`usuario_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` CHANGE \`estado\` \`estado\` enum ('pendiente', 'resuelto') NULL DEFAULT 'pendiente'`);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` CHANGE \`mensaje\` \`mensaje\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` DROP COLUMN \`asunto\``);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` ADD \`asunto\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` CHANGE \`usuario_id\` \`usuario_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` CHANGE \`leida\` \`leida\` tinyint(1) NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` CHANGE \`mensaje\` \`mensaje\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`proyectos\` CHANGE \`submodulo_id\` \`submodulo_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`proyectos\` CHANGE \`modulo_id\` \`modulo_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`proyectos\` CHANGE \`usuario_id\` \`usuario_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`proyectos\` CHANGE \`fecha_inicio\` \`fecha_inicio\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`proyectos\` DROP COLUMN \`ubicacion\``);
        await queryRunner.query(`ALTER TABLE \`proyectos\` ADD \`ubicacion\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`proyectos\` DROP COLUMN \`nombre\``);
        await queryRunner.query(`ALTER TABLE \`proyectos\` ADD \`nombre\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` CHANGE \`proyecto_id\` \`proyecto_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`reportes\` CHANGE \`formato_id\` \`formato_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`reportes\` CHANGE \`proyecto_id\` \`proyecto_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`formatos_reporte\` DROP COLUMN \`nombre\``);
        await queryRunner.query(`ALTER TABLE \`formatos_reporte\` ADD \`nombre\` varchar(10) NULL`);
        await queryRunner.query(`ALTER TABLE \`transacciones\` CHANGE \`categoria_id\` \`categoria_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`transacciones\` CHANGE \`proyecto_id\` \`proyecto_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`transacciones\` DROP COLUMN \`descripcion\``);
        await queryRunner.query(`ALTER TABLE \`transacciones\` ADD \`descripcion\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`transacciones\` CHANGE \`fecha\` \`fecha\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`categorias_transaccion\` DROP COLUMN \`nombre\``);
        await queryRunner.query(`ALTER TABLE \`categorias_transaccion\` ADD \`nombre\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`tareas\` CHANGE \`proyecto_id\` \`proyecto_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`tareas\` CHANGE \`recordatorio\` \`recordatorio\` tinyint(1) NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`tareas\` CHANGE \`fecha\` \`fecha\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`tareas\` DROP COLUMN \`titulo\``);
        await queryRunner.query(`ALTER TABLE \`tareas\` ADD \`titulo\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`agendas\` CHANGE \`proyecto_id\` \`proyecto_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`eventos\` CHANGE \`tipo_evento_id\` \`tipo_evento_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`eventos\` CHANGE \`proyecto_id\` \`proyecto_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`eventos\` CHANGE \`tiene_gasto\` \`tiene_gasto\` tinyint(1) NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`eventos\` CHANGE \`fecha_evento\` \`fecha_evento\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`eventos\` CHANGE \`descripcion\` \`descripcion\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tipos_evento\` DROP INDEX \`IDX_4752b8447cc578fd3719ab5499\``);
        await queryRunner.query(`ALTER TABLE \`tipos_evento\` DROP COLUMN \`nombre\``);
        await queryRunner.query(`ALTER TABLE \`tipos_evento\` ADD \`nombre\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` CHANGE \`proyecto_id\` \`proyecto_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`parametros_proyecto\` CHANGE \`proyecto_id\` \`proyecto_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`parametros_proyecto\` DROP COLUMN \`valor\``);
        await queryRunner.query(`ALTER TABLE \`parametros_proyecto\` ADD \`valor\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`parametros_proyecto\` DROP COLUMN \`parametro_nombre\``);
        await queryRunner.query(`ALTER TABLE \`parametros_proyecto\` ADD \`parametro_nombre\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`modulos\` DROP INDEX \`IDX_9dd861f2d25942a1c2c563af05\``);
        await queryRunner.query(`ALTER TABLE \`modulos\` DROP COLUMN \`nombre\``);
        await queryRunner.query(`ALTER TABLE \`modulos\` ADD \`nombre\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` CHANGE \`modulo_id\` \`modulo_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` CHANGE \`usuario_id\` \`usuario_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` CHANGE \`contenido\` \`contenido\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` DROP COLUMN \`titulo\``);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` ADD \`titulo\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`submodulos\` CHANGE \`modulo_id\` \`modulo_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`submodulos\` DROP COLUMN \`nombre\``);
        await queryRunner.query(`ALTER TABLE \`submodulos\` ADD \`nombre\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuario_roles\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP COLUMN \`password\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` DROP COLUMN \`adjunto_url\``);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` DROP COLUMN \`respuesta\``);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` DROP COLUMN \`tipo\``);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` DROP COLUMN \`titulo\``);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`proyectos\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`proyectos\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`proyectos\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` DROP COLUMN \`activa\``);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` DROP COLUMN \`mensaje\``);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` DROP COLUMN \`condicion\``);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` DROP COLUMN \`nombre\``);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`reportes\` DROP COLUMN \`archivo_url\``);
        await queryRunner.query(`ALTER TABLE \`reportes\` DROP COLUMN \`datos\``);
        await queryRunner.query(`ALTER TABLE \`reportes\` DROP COLUMN \`fecha_fin\``);
        await queryRunner.query(`ALTER TABLE \`reportes\` DROP COLUMN \`fecha_inicio\``);
        await queryRunner.query(`ALTER TABLE \`reportes\` DROP COLUMN \`titulo\``);
        await queryRunner.query(`ALTER TABLE \`reportes\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`reportes\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`reportes\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`formatos_reporte\` DROP COLUMN \`descripcion\``);
        await queryRunner.query(`ALTER TABLE \`formatos_reporte\` DROP COLUMN \`estructura\``);
        await queryRunner.query(`ALTER TABLE \`formatos_reporte\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`formatos_reporte\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`formatos_reporte\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`transacciones\` DROP COLUMN \`comprobante_url\``);
        await queryRunner.query(`ALTER TABLE \`transacciones\` DROP COLUMN \`monto\``);
        await queryRunner.query(`ALTER TABLE \`transacciones\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`transacciones\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`transacciones\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`categorias_transaccion\` DROP COLUMN \`descripcion\``);
        await queryRunner.query(`ALTER TABLE \`categorias_transaccion\` DROP COLUMN \`tipo\``);
        await queryRunner.query(`ALTER TABLE \`categorias_transaccion\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`categorias_transaccion\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`categorias_transaccion\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`tareas\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`tareas\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`tareas\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`agendas\` DROP COLUMN \`tipo\``);
        await queryRunner.query(`ALTER TABLE \`agendas\` DROP COLUMN \`fecha\``);
        await queryRunner.query(`ALTER TABLE \`agendas\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`agendas\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`agendas\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`eventos\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`eventos\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`eventos\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`tipos_evento\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`tipos_evento\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`tipos_evento\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` DROP COLUMN \`roi\``);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` DROP COLUMN \`rentabilidad_neta\``);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` DROP COLUMN \`gastos_totales\``);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` DROP COLUMN \`ingresos_totales\``);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` DROP COLUMN \`inversion_inicial\``);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` DROP COLUMN \`fecha\``);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`parametros_proyecto\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`parametros_proyecto\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`parametros_proyecto\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`modulos\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`modulos\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`modulos\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` DROP COLUMN \`comentario_padre_id\``);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` DROP COLUMN \`likes\``);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` DROP COLUMN \`imagen_url\``);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`submodulos\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`submodulos\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`submodulos\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` ADD \`fecha_creacion\` timestamp NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` ADD \`fecha_creacion\` timestamp NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` ADD \`fecha_creacion\` timestamp NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` ADD \`tipo_alerta\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` ADD \`mensaje_alerta\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`reportes\` ADD \`url_archivo\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`reportes\` ADD \`fecha_generado\` timestamp NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`reportes\` ADD \`tipo_reporte\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`transacciones\` ADD \`valor\` decimal NULL`);
        await queryRunner.query(`ALTER TABLE \`transacciones\` ADD \`tipo\` enum ('gasto', 'ingreso') NULL`);
        await queryRunner.query(`ALTER TABLE \`agendas\` ADD \`fecha_evento\` timestamp NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` ADD \`fecha_calculo\` timestamp NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` ADD \`rentabilidad\` decimal NULL`);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` ADD \`fecha_creado\` timestamp NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`CREATE INDEX \`usuario_id\` ON \`usuario_roles\` (\`usuario_id\`)`);
        await queryRunner.query(`CREATE INDEX \`rol_id\` ON \`usuario_roles\` (\`rol_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`email\` ON \`usuarios\` (\`email\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`nombre\` ON \`roles\` (\`nombre\`)`);
        await queryRunner.query(`CREATE INDEX \`usuario_id\` ON \`soporte_tecnico\` (\`usuario_id\`)`);
        await queryRunner.query(`CREATE INDEX \`usuario_id\` ON \`notificaciones\` (\`usuario_id\`)`);
        await queryRunner.query(`CREATE INDEX \`usuario_id\` ON \`proyectos\` (\`usuario_id\`)`);
        await queryRunner.query(`CREATE INDEX \`submodulo_id\` ON \`proyectos\` (\`submodulo_id\`)`);
        await queryRunner.query(`CREATE INDEX \`modulo_id\` ON \`proyectos\` (\`modulo_id\`)`);
        await queryRunner.query(`CREATE INDEX \`proyecto_id\` ON \`alertas_inteligentes\` (\`proyecto_id\`)`);
        await queryRunner.query(`CREATE INDEX \`proyecto_id\` ON \`reportes\` (\`proyecto_id\`)`);
        await queryRunner.query(`CREATE INDEX \`formato_id\` ON \`reportes\` (\`formato_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`nombre\` ON \`formatos_reporte\` (\`nombre\`)`);
        await queryRunner.query(`CREATE INDEX \`proyecto_id\` ON \`transacciones\` (\`proyecto_id\`)`);
        await queryRunner.query(`CREATE INDEX \`categoria_id\` ON \`transacciones\` (\`categoria_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`nombre\` ON \`categorias_transaccion\` (\`nombre\`)`);
        await queryRunner.query(`CREATE INDEX \`proyecto_id\` ON \`tareas\` (\`proyecto_id\`)`);
        await queryRunner.query(`CREATE INDEX \`tarea_id\` ON \`agendas\` (\`tarea_id\`)`);
        await queryRunner.query(`CREATE INDEX \`proyecto_id\` ON \`agendas\` (\`proyecto_id\`)`);
        await queryRunner.query(`CREATE INDEX \`evento_id\` ON \`agendas\` (\`evento_id\`)`);
        await queryRunner.query(`CREATE INDEX \`tipo_evento_id\` ON \`eventos\` (\`tipo_evento_id\`)`);
        await queryRunner.query(`CREATE INDEX \`proyecto_id\` ON \`eventos\` (\`proyecto_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`nombre\` ON \`tipos_evento\` (\`nombre\`)`);
        await queryRunner.query(`CREATE INDEX \`proyecto_id\` ON \`rentabilidad_proyecto\` (\`proyecto_id\`)`);
        await queryRunner.query(`CREATE INDEX \`proyecto_id\` ON \`parametros_proyecto\` (\`proyecto_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`nombre\` ON \`modulos\` (\`nombre\`)`);
        await queryRunner.query(`CREATE INDEX \`usuario_id\` ON \`foro_comentarios\` (\`usuario_id\`)`);
        await queryRunner.query(`CREATE INDEX \`modulo_id\` ON \`foro_comentarios\` (\`modulo_id\`)`);
        await queryRunner.query(`CREATE INDEX \`modulo_id\` ON \`submodulos\` (\`modulo_id\`)`);
        await queryRunner.query(`ALTER TABLE \`usuario_roles\` ADD CONSTRAINT \`usuario_roles_ibfk_2\` FOREIGN KEY (\`rol_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`usuario_roles\` ADD CONSTRAINT \`usuario_roles_ibfk_1\` FOREIGN KEY (\`usuario_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`soporte_tecnico\` ADD CONSTRAINT \`soporte_tecnico_ibfk_1\` FOREIGN KEY (\`usuario_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` ADD CONSTRAINT \`notificaciones_ibfk_1\` FOREIGN KEY (\`usuario_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`proyectos\` ADD CONSTRAINT \`proyectos_ibfk_3\` FOREIGN KEY (\`submodulo_id\`) REFERENCES \`submodulos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`proyectos\` ADD CONSTRAINT \`proyectos_ibfk_2\` FOREIGN KEY (\`modulo_id\`) REFERENCES \`modulos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`proyectos\` ADD CONSTRAINT \`proyectos_ibfk_1\` FOREIGN KEY (\`usuario_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`alertas_inteligentes\` ADD CONSTRAINT \`alertas_inteligentes_ibfk_1\` FOREIGN KEY (\`proyecto_id\`) REFERENCES \`proyectos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reportes\` ADD CONSTRAINT \`reportes_ibfk_2\` FOREIGN KEY (\`formato_id\`) REFERENCES \`formatos_reporte\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reportes\` ADD CONSTRAINT \`reportes_ibfk_1\` FOREIGN KEY (\`proyecto_id\`) REFERENCES \`proyectos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transacciones\` ADD CONSTRAINT \`transacciones_ibfk_2\` FOREIGN KEY (\`categoria_id\`) REFERENCES \`categorias_transaccion\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transacciones\` ADD CONSTRAINT \`transacciones_ibfk_1\` FOREIGN KEY (\`proyecto_id\`) REFERENCES \`proyectos\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tareas\` ADD CONSTRAINT \`tareas_ibfk_1\` FOREIGN KEY (\`proyecto_id\`) REFERENCES \`proyectos\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`agendas\` ADD CONSTRAINT \`agendas_ibfk_3\` FOREIGN KEY (\`tarea_id\`) REFERENCES \`tareas\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`agendas\` ADD CONSTRAINT \`agendas_ibfk_2\` FOREIGN KEY (\`evento_id\`) REFERENCES \`eventos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`agendas\` ADD CONSTRAINT \`agendas_ibfk_1\` FOREIGN KEY (\`proyecto_id\`) REFERENCES \`proyectos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`eventos\` ADD CONSTRAINT \`eventos_ibfk_2\` FOREIGN KEY (\`tipo_evento_id\`) REFERENCES \`tipos_evento\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`eventos\` ADD CONSTRAINT \`eventos_ibfk_1\` FOREIGN KEY (\`proyecto_id\`) REFERENCES \`proyectos\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rentabilidad_proyecto\` ADD CONSTRAINT \`rentabilidad_proyecto_ibfk_1\` FOREIGN KEY (\`proyecto_id\`) REFERENCES \`proyectos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`parametros_proyecto\` ADD CONSTRAINT \`parametros_proyecto_ibfk_1\` FOREIGN KEY (\`proyecto_id\`) REFERENCES \`proyectos\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` ADD CONSTRAINT \`foro_comentarios_ibfk_2\` FOREIGN KEY (\`modulo_id\`) REFERENCES \`modulos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`foro_comentarios\` ADD CONSTRAINT \`foro_comentarios_ibfk_1\` FOREIGN KEY (\`usuario_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`submodulos\` ADD CONSTRAINT \`submodulos_ibfk_1\` FOREIGN KEY (\`modulo_id\`) REFERENCES \`modulos\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
